### ISSUE TITLE
Version 2.1.0 BC break with ZF2

### ISSUE THREAD

**Issue by athlan** [outeredge/SwaggerModule#12]
Releare 2.1.0 breaks backward compability with ZF2, because of commit:
https://github.com/outeredge/SwaggerModule/commit/bfa6f7aa39288e1375e10765f75d3b0da377b1d5

In ZF 2.3.1 there is no `Zend\ServiceManager\Factory\FactoryInterface;`, instead of this there is `Zend\ServiceManager\FactoryInterface;`

In my opinion, version 2.1.0 should be 3.x.

**Comment by davidwindell** [comment]
@athlan You're quite right. Are you able to raise a PR that uses the `Zend\ServiceManager\FactoryInterface` shim so that we can support both ZF2 and ZF3?

https://github.com/zendframework/zend-servicemanager/blob/master/src/FactoryInterface.php

**Comment by athlan** [comment]
Let's discuss about implementation.
http://zendframework.github.io/zend-servicemanager/migration/#factories

Mentioned commit bfa6f7a introduces the factory that uses ```Interop\Container\ContainerInterface``` which has not been supported in ZF2. I cannot re-use just implemented factory and directly implement additional shim interface (renamed of course) in existing class to support ZF2.

Possible implementations:
1, I could create a new factory (implement old ZF2 interface which will be shim for ZF3) and create factory of factories (depending of ZF2/ZF3). This will separate both implementations of different interfaces (ZF2/ZF3 shim and new ZF3) and gives an opportunity to remove ZF2 support in the future simply by deleting class.

2. Or I could implement shim interface in exising implementation and get rid of ZF3 interface. But shim interface is marked as deprecated and this will introduce new deprecated code. 

Which implementation will be more suitable from your perspective? I would prefer first solution, because second is introducing unnecessary technical debt in my opinion.

**Comment by athlan** [comment]
Pull request has been prepared.

**Comment by davidwindell** [comment]
Thanks @athlan, I'll review this early next week for you.

**Comment by athlan** [comment]
Bump.

**Comment by davidwindell** [comment]
Fixed in 70ebf54650e0114a2575c264f8248d593469009a
