### ISSUE TITLE
Not compitable with zf3

### ISSUE THREAD

**Issue by waqarorakzai** [outeredge/SwaggerModule#15]
I just included it using composer and it is giving me this error
`Fatal error: Declaration of SwaggerModule\Controller\DocumentationControllerFactory::__invoke(Interop\Container\ContainerInterface $container, $requestedName) must be compatible with Zend\ServiceManager\Factory\FactoryInterface::__invoke(Interop\Container\ContainerInterface $container, $requestedName, ?array $options = NULL) in E:\xampp\htdocs\pi-v3\vendor\outeredge\swagger-module\src\SwaggerModule\Controller\DocumentationControllerFactory.php on line 27`

**Comment by davidwindell** [comment]
This was working so I guess there has been a breaking change in ServiceManager. Happy to accept a PR for this :)

**Comment by Xerkus** [comment]
This is a breaking change in PHP 7.3. Optional parameters can no longer be omitted in overriding/implementing methods

**Comment by davidwindell** [comment]
PR's welcome!
