### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by someother1** [outeredge/SwaggerModule#8]
This Module does not work anymore with latest Zend2 and Swagger 2.0

Do you mind to update it in the future?

**Comment by davidwindell** [comment]
@someother1 It would be great if you can provide a pull request for this!

**Comment by xl32** [comment]
I think this can be fixed with https://github.com/outeredge/SwaggerModule/pull/9

**Comment by davidwindell** [comment]
Thanks @xl32! that's been merged and tagged as 2.0.
